routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('login/locked', 'Auth\LoginController@locked')->middleware('auth')->name('login.locked');
Route::post('login/locked', 'Auth\LoginController@unlock')->name('login.unlock');

Route::get('/',[
    'as' => 'index',
    'uses' => 'HomeController@index'
]);

Route::resource('employee','EmployeeController');

Route::get('settings',[
    'as' => 'settings',
    'uses' => 'SettingsController'
]);

Route::resource('user_role','UserRoleController');

Route::resource('module_permission','ModulePermissionController');

Route::resource('client','ClientController');

Route::resource('identity_card_type', 'IdentityCardTypeController');

Route::get('company',[
    'as' => 'company.show',
    'uses' => 'CompanyController@show'
]);

Route::resource('event', 'EventController', [
    'except' => [ 'show']
]);

Route::get('event/delete_event/{id}',[
    'as' => 'event.delete_event',
    'uses' => 'EventController@delete'
]);

Route::get('event/calander_view',[
    'as' => 'event.calander_view',
    'uses' => 'EventController@calander_view'
]);

Route::resource('product_unit', 'ProductUnitController');
Route::resource('product', 'ProductController');
Route::resource('supplier', 'SupplierController');
Route::resource('supply', 'SupplyController');
Route::resource('sell', 'SellController');

Route::resource('cashbook', 'CashBookController')->only([
    'index'
]);

Route::resource('stock', 'StockController')->only([
    'index'
]);

Route::get('stock/get_stock_by_product_id/{id}',[
    'as' => 'stock.get_stock_by_product_id',
    'uses' => 'StockController@getStockByProductId'
]);

Route::get('product/get_unit_by_id/{id}',[
    'as' => 'product.get_unit_by_id',
    'uses' => 'ProductController@getUnitById'
]);

Route::get('stock/stock_exists',[
    'as' => 'stock.stock_exists',
    'uses' => 'StockController@stockExists'
]);

Route::get('sell/{id}/print',[
    'as' => 'sell.print',
    'uses' => 'SellController@print'
]);

Route::get('stock/out_add_to_cart',[
    'as' => 'stock.out_add_to_cart',
    'uses' => 'StockController@outAddToCart'
]);

Route::get('stock/in_add_to_cart',[
    'as' => 'stock.in_add_to_cart',
    'uses' => 'StockController@inAddToCart'
]);

Route::get('stock/remove_from_cart/{id}',[
    'as' => 'stock.remove_from_cart',
    'uses' => 'StockController@removeFromCart'
]);

Route::get('stock/stock_check/{id}',[
    'as' => 'stock.stock_check',
    'uses' => 'StockController@getStockUnits'
]);

Route::get('stock/dashboard',[
    'as' => 'stock.dashboard',
    'uses' => 'StockController@dashboard'
]);

Route::get('stock/sell-graph-data',[
    'as' => 'stock.sell-graph-data',
    'uses' => 'StockController@sellGraphData'
]);


Route::resource('salary', 'SalaryController');
Route::resource('salary_period', 'SalaryPeriodController');

Route::get('salary/{id}/print',[
    'as' => 'salary.print',
    'uses' => 'SalaryController@print'
]);

Route::get('supply/{id}/print',[
    'as' => 'supply.print',
    'uses' => 'SupplyController@print'
]);

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Model\Supplier;
use App\Model\SupplierAttachment;
use Illuminate\Http\Request;
use App\Model\IdentityCardType;

use App\Type\StatusType;
use App\Type\AttachmentType;
use App\Type\CommonType;

use App\Util\CommonFunc;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;

use Intervention\Image\ImageManagerStatic as Image;

class SupplierController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view', Supplier::class);

        if($request['search-status'] == null){
            $request['search-status'] =StatusType::Active;
        }
        
        $suppliers = Supplier::select('tbl_supplier.*')
                ->when(!empty($request->input('search-name')) , function ($query) use($request){
                    return $query->where('tbl_supplier.NAME', 'like','%'. $request->input('search-name').'%' );
                })
                ->where('tbl_supplier.STATUS', '=',$request->input('search-status') )
                ->orderBy('INSERT_DATETIME', 'DESC')            
                ->paginate(CommonFunc::getPaginationSize());

        return view('supplier.list')->with('suppliers',$suppliers)
                                 ->with('request',$request);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Supplier::class);

        $supplier = new Supplier();        
        $identity_card_list=IdentityCardType::orderBy('display_name','asc')->pluck('display_name','id');

        return view('supplier.create')->with('supplier',$supplier)
                                    ->with('identity_card_list',$identity_card_list);                                 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {        
        $this->authorize('create', Supplier::class);

        $this->validate($request,[
            'name' => 'required',
            'identity_card_type_id' => 'required',
            'identity_card_number' => 'required|regex:/(^[A-Za-z0-9 ]+$)+/|unique:tbl_supplier',
            'mobile1' => 'required|regex:/(0)[0-9]{9}/|unique:tbl_supplier',
            'address1'  => 'required',
            'email' => 'nullable|string|email|max:255|unique:tbl_supplier',
            'image-01' => 'image|mimes:jpeg,png,jpg,gif,svg',              
        ]);
        
        $supplier = new Supplier;
        $supplier->id=CommonFunc::getPrimaryKey();
        $supplier->name = $request->input('name');
        $supplier->identity_card_type_id = $request->input('identity_card_type_id');
        $supplier->identity_card_number = $request->input('identity_card_number');
        $supplier->mobile1 = $request -> input('mobile1');
        $supplier->address1 = $request->input('address1');
        $supplier->email=$request->input('email');
        $supplier->joined_date=$request->input('joined_date');
        $supplier->comment=$request->input('comment');
        $supplier->status=StatusType::Active;
               
        $supplier->save();

        if($request->hasFile('image-01')){
            $fileNameWithExt = $request -> file('image-01')->getSupplierOriginalName();
            $filename = pathinfo($fileNameWithExt,PATHINFO_FILENAME);
            $extention = $request ->file('image-01')->getSupplierOriginalExtension();
            $fileNameToStore01 = $filename.'_'.CommonFunc::getPrimaryKey().'.'.$extention;

            $image= $request->file('image-01');
            $image_resize = Image::make($image->getRealPath());              
            $image_resize->resize(CommonType::ImageWidth, CommonType::ImageHight);
            $image_resize->save(public_path('/storage/images/supplier_attachments/' .$fileNameToStore01));

            if (!empty($supplier->supplier_photo()->id))
            {
                $supplierImage=$supplier->supplier_photo();
                Storage::delete('public/images/supplier_attachments/'.$supplierImage->path);
                $supplierImage->path=$fileNameToStore01;
                $supplierImage->save();
            }else{
                $supplierImage=new SupplierAttachment();
                $supplierImage->id=CommonFunc::getPrimaryKey();
                $supplierImage->path=$fileNameToStore01;
                $supplierImage->supplier_id=$supplier->id;
                $supplierImage->attachment_types_id=AttachmentType::SupplierPhoto;
                $supplierImage->status=StatusType::Active;
                $supplierImage->save();
            }
        }

        return redirect()->route('supplier.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->authorize('view', Supplier::class);

        $supplier =Supplier::find($id);
        
        return view('supplier.view')->with('supplier',$supplier);;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->authorize('update', Supplier::class);

        $supplier = Supplier::find($id);
        $identity_card_list=IdentityCardType::orderBy('display_name','asc')->pluck('display_name','id');

        return view('supplier.create')->with('supplier',$supplier)
                                    ->with('identity_card_list',$identity_card_list); ; 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->authorize('update', Supplier::class);

        $this->validate($request,[
            'name' => 'required',
            'identity_card_type_id' => 'required',
            'identity_card_number' => 'required|regex:/(^[A-Za-z0-9 ]+$)+/|unique:tbl_supplier,identity_card_number,'.$id,
            'mobile1' => 'required|regex:/(0)[0-9]{9}/|unique:tbl_supplier,mobile1,'.$id,
            'address1'  => 'required',
            'email' => 'nullable|string|email|max:255|unique:tbl_supplier,email,'.$id,
            'image-01' => 'image|mimes:jpeg,png,jpg,gif,svg',              
        ]);
        
        $supplier = Supplier::find($id);
        $supplier->name = $request->input('name');
        $supplier->identity_card_type_id = $request->input('identity_card_type_id');
        $supplier->identity_card_number = $request->input('identity_card_number');
        $supplier->mobile1 = $request -> input('mobile1');
        $supplier->address1 = $request->input('address1');
        $supplier->email=$request->input('email');
        $supplier->joined_date=$request->input('joined_date');
        $supplier->comment=$request->input('comment');
        $supplier->status=StatusType::Active;
               
        $supplier->save();

        if($request->hasFile('image-01')){
            $fileNameWithExt = $request -> file('image-01')->getClientOriginalName();
            $filename = pathinfo($fileNameWithExt,PATHINFO_FILENAME);
            $extention = $request ->file('image-01')->getClientOriginalName();
            $fileNameToStore01 = $filename.'_'.CommonFunc::getPrimaryKey().'.'.$extention;
            
            $image= $request->file('image-01');
            $image_resize = Image::make($image->getRealPath());              
            $image_resize->resize(CommonType::ImageWidth, CommonType::ImageHight);
            $image_resize->save(public_path('/storage/images/supplier_attachments/' .$fileNameToStore01));

            if (!empty($supplier->supplier_photo()->id))
            {
                $supplierImage=$supplier->supplier_photo();
                Storage::delete('public/images/supplier_attachments/'.$supplierImage->path);
                $supplierImage->path=$fileNameToStore01;
                $supplierImage->save();
            }else{
                $supplierImage=new SupplierAttachment();
                $supplierImage->id=CommonFunc::getPrimaryKey();
                $supplierImage->path=$fileNameToStore01;
                $supplierImage->supplier_id=$supplier->id;
                $supplierImage->attachment_types_id=AttachmentType::SupplierPhoto;
                $supplierImage->status=StatusType::Active;
                $supplierImage->save();
            }
        }

        return redirect()->route('supplier.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function destroy(Supplier $supplier)
    {
        $this->authorize('delete', Supplier::class);
    }
}

resources/views/supplier/create.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
        <h1>
            Supplier
            <small>Handle all Supplier Resources</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{ route('supplier.index') }}"><i class="fa fa-smile-o"></i> Supplier</a></li>            
            @if(!isset($supplier->id))
                <li class="active">Add Supplier</li>
            @else   
                <li class="active">Edit Supplier</li>
            @endif     
        </ol>
</section>
<section class="content">
    <div class="container box">
            @if(!isset($supplier->id))
            <div class="box-header">
                <h3 class="box-title">Supplier Basic Information</h3>
            </div>
            <div class="box-body">
                    {!! Form::open(['route' => ['supplier.store'],'method' => 'POST','enctype' => 'multipart/form-data']) !!}
            @else
            <div class="box-header">
                <h3 class="box-title">Edit Supplier Basic Information of :: <b>{{ $supplier->name }} </b></h3>
            </div>
            <div class="box-body">
                    {!! Form::open(['route' => ['supplier.update',$supplier->id],'method' => 'POST','enctype' => 'multipart/form-data']) !!}
                    {!! Form::hidden('_method','PUT') !!}
            @endif
                <div class='form-group row'>
                    {{Form::label('name','Name',['class' => 'col-sm-2 col-form-label text-md-right'])}}
                    <div class="col-md-8">
                        {{Form::text('name', $supplier->name ,['class' => 'form-control','placeholder'=>'Name','required'=> 'true'])}}
                        @if ($errors->has('name'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div> 
                </div>

                <div class="form-group row">
                    {{Form::label('identity_card_type_id','Identity Card Type',['class' => 'col-sm-2 col-form-label text-md-right'])}}
                    <div class="col-md-8">
                        {!!Form::select('identity_card_type_id', $identity_card_list, $supplier->identity_card_type_id, ['placeholder' => 'Please select ...','class' => 'form-control','required'=> 'true'])!!}
                        @if ($errors->has('identity_card_type_id'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('identity_card_type_id') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class='form-group row'>
                    {{Form::label('identity_card_number','Identity Card Number',['class' => 'col-sm-2 col-form-label text-md-right'])}}
                    <div class="col-md-8">
                        {{Form::text('identity_card_number', $supplier->identity_card_number ,['class' => 'form-control','placeholder'=>'Identity Card Number','required'=> 'true'])}}
                        @if ($errors->has('identity_card_number'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('identity_card_number') }}</strong>
                            </span>
                        @endif
                    </div> 
                </div>

                <div class='form-group row'>
                    {{Form::label('mobile1','Mobile',['class' => 'col-sm-2 col-form-label text-md-right'])}}
                    <div class="col-md-8">
                        {{Form::text('mobile1', $supplier->mobile1 ,['class' => 'form-control','placeholder'=>'Mobile','required'=> 'true'])}}
                        @if ($errors->has('mobile1'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('mobile1') }}</strong>
                            </span>
                        @endif
                    </div> 
                </div>

                <div class='form-group row'>
                    {{Form::label('email','Email',['class' => 'col-sm-2 col-form-label text-md-right'])}}
                    <div class="col-md-8">
                        {{Form::email('email', $supplier->email ,['class' => 'form-control','placeholder'=>'Supplier Email'])}}
                        @if ($errors->has('email'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('email') }}</strong>
                            </span>
                        @endif
                    </div> 
                </div>

                <div class='form-group row'>
                    {{Form::label('address1','Address',['class' => 'col-sm-2 col-form-label text-md-right'])}}
                    <div class="col-md-8">
                        {{Form::textarea('address1', $supplier->address1 ,['id'=>'article-ckeditor','class' => 'form-control','placeholder'=>'Address','rows'=>4,'required'=> 'true'])}}
                        @if ($errors->has('address1'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('address1') }}</strong>
                            </span>
                        @endif
                    </div> 
                </div>

                <div class='form-group row'>
                    {{Form::label('joined_date','Joined Date',['class' => 'col-sm-2 col-form-label text-md-right'])}}
                    <div class="col-md-3">
                        <div class="input-group date" data-date-format="yyyy-mm-dd" id="datetimepicker3">
                            {{Form::text('joined_date', (!$supplier->joined_date) ? $supplier->joined_date : $supplier->joined_date->format('Y-m-d')  ,['class' => 'form-control','required'=> 'true','placeholder' => 'Joined Date','readonly'])}}
                            <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                        </div>
                        
                        @if ($errors->has('joined_date'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('joined_date') }}</strong>
                            </span>
                        @endif
                    </div> 
                </div>

                <div class='form-group row'>
                    {{Form::label('image-01','Photo',['class' => 'col-sm-2 col-form-label text-md-right'])}}
                    <div class="col-md-3">                                              
                        <img id="image01" src="{{route('index')}}/storage/images/supplier_attachments/{{ $supplier->supplier_photo()->path }}" class="imagePreview"/>                                             
                        {{ Form::file('image-01',['accept' => 'image/*','onchange' => 'readURL(this,"#image01")']) }}
                        @if ($errors->has('image-01'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('image-01') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class='form-group row'>
                    {{Form::label('comment','Comment',['class' => 'col-sm-2 col-form-label text-md-right'])}}
                    <div class="col-md-8">
                        {{Form::textarea('comment', $supplier->comment ,['id'=>'article-ckeditor','class' => 'form-control','placeholder'=>'Comment','rows'=>4])}}
                        @if ($errors->has('comment'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('comment') }}</strong>
                            </span>
                        @endif
                    </div> 
                </div>

            </div>
    </div>            
</section>

<div class="row">
    <div class="form-group">
        <div class="col-sm-12 col-sm-offset-1">
            {{Form::reset('Reset',['class' => 'btn btn-default'])}}
            {{Form::submit('Submit',['class' => 'btn btn-primary'])}}
        </div>
    </div>    
</div>
<br>
<br>
{!! Form::close() !!}

<script type="text/javascript">
    $("#supplier").addClass("active");

    $('#datetimepicker3').datetimepicker({
        format:'yyyy-mm-dd',
        pickTime: false,
        minView: 2,
        autoclose: 1,
    });
</script>
@endsection

resources/views/supplier/list.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
            <h1>
                Supplier
                <small>Handle all Supplier Resources</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="{{ route('supplier.index') }}"><i class="fa fa-smile-o"></i> Supplier</a></li>  
                <li class="active">List Supplier</li>    
            </ol>
    </section>
    <section class="content">
        <div class="container box">
            <div class="box-header">
                <h3 class="box-title">Supplier List</h3>   
            </div>            
            <div class="box-body">
                <!-- form start -->
                {!! Form::open(['route' => 'supplier.index','method' => 'GET','enctype' => 'multipart/form-data']) !!}
                    {{Form::label('search-name','Name',['class' => 'col-sm-1 control-label'])}}
                    
                    <div class="col-sm-3">
                        <div class="input-group">
                            {{Form::text('search-name', $request->input('search-name') ,['class' => 'form-control','placeholder'=>'Name'])}}
                            <span id="btnTextClear" class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                        </div>
                        <script>
                            $(".glyphicon-remove").click(function(){
                                $("#search-name").val('');
                            });
                        </script>
                    </div>

                    {{Form::label('search-status','Status',['class' => 'col-sm-1 control-label'])}}

                    <div class="col-sm-2">
                        {!!Form::select('search-status',App\Type\StatusType::getKeys(), $request->input('search-status'), ['class' => 'form-control'])!!}
                    </div>

                    <div class="col-sm-1">
                    {{Form::submit('Search',['class' => 'btn btn-info center-block'])}}
                    </div>
                {!! Form::close() !!}
                </div>
                @php ($i = 1)
                @if(count($suppliers) > 0)
                <!-- /.box-header -->
                <div class="table-responsive" style="overflow: auto">
                <table id="dataTable" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Idenity</th>
                        <th>Mobile</th>
                        <th>Address</th>
                        <th>Joined Date</th>
                        <th>Comment</th>
                        <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($suppliers as $supplier)
                    <tr>
                        <td>{{ (($suppliers->currentpage()-1) * $suppliers->perpage()) + $i++  }}</td>
                        <td class="bigColumn">{{$supplier->name}}</td>
                        <td>{{$supplier->DisplayIdentityCard}}</td>
                        <td>{{$supplier->mobile1}}</td>
                        <td class="bigColumn">{{$supplier->address1}}</td>
                        <td>{{$supplier->JoinedDateFormated}}</td>
                        <td class="bigColumn">{{$supplier->comment}}</td>
                        <td title="{{ $supplier->recordBy()}}">
                            <a href="{{ route('supplier.show', ['id' => $supplier->id]) }}" class="btn btn-info btn-xs">
                                <i class="fa fa-info-circle"></i> View
                            </a>
                            <a href="{{ route('supplier.edit', ['id' => $supplier->id]) }}" class="btn btn-warning btn-xs" data-toggle="confirmation">
                                <i class="fa fa-pencil-square-o"></i> Edit
                            </a>
                        </td>                       
                    </tr>
                    @endforeach    
                    </tbody>
                </table>
                </div>
            <div class="centerBlock">
                {{ $suppliers->appends(Request::except('page'))->links() }}
            </div>
            @else
                <div class="alert alert-danger"> No Records Found ! </div>
            @endif
        </div>
    </section>

<script type="text/javascript">
    $("#supplier").addClass("active");
</script>
@endsection

resources/views/supplier/view.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
            <h1>
                Supplier
                <small>Handle all Supplier Resources</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="{{ route('supplier.index') }}"><i class="fa fa-smile-o"></i> Supplier</a></li>  
                <li class="active">List Supplier</li>    
            </ol>
    </section>
    <section class="content">
        <div class="container box">
            <div class="box-header">
                <h3 class="box-title">Supplier Deatails of :: <b>{{ $supplier->name }} </b> </h3>
                <div class="semi pull-right">
                    <a href="{{ route('supplier.edit', ['id' => $supplier->id]) }}" class="btn btn-warning btn-xs" data-toggle="confirmation">
                        <i class="fa fa-pencil-square-o"></i> Edit
                    </a>
                </div>    
            </div>
            <div class="box-body">
                <div class="col-md-12" style="margin: 10px 0px;">
                    <img id="image01" src="{{route('index')}}/storage/images/supplier_attachments/{{ $supplier->supplier_photo()->path }}" class="imagePreview"/> 
                </div>
                <div class="col-md-6">
                    <div class="table-responsive">
                        <table class="table table-striped simple">
                            <tbody>                                            
                                <tr>
                                    <td>Name: </td>
                                    <td>{{ $supplier->name }}</td>
                                </tr>
                                <tr>
                                    <td>Identity Card Deatails: </td>
                                    <td>{{ $supplier->DisplayIdentityCard }}</td>
                                </tr>
                                <tr>
                                    <td>Mobile: </td>
                                    <td>{{ $supplier->mobile1 }}</td>
                                </tr>
                                <tr>
                                    <td>Address: </td>
                                    <td>{{ $supplier->address1 }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="table-responsive">
                        <table class="table table-striped simple">
                            <tbody> 
                                <tr>
                                    <td>Joined Date: </td>
                                    <td>{{ $supplier->joined_date }}</td>
                                </tr>
                                <tr>
                                    <td>Comment: </td>
                                    <td>{{ $supplier->comment }}</td>
                                </tr>                                             
                            </tbody>
                        </table>
                    </div>
                </div>
            </div> 
        </div>
    </section> 

<script type="text/javascript">
    $("#supplier").addClass("active");
</script>
@endsection