routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('login/locked', 'Auth\LoginController@locked')->middleware('auth')->name('login.locked');
Route::post('login/locked', 'Auth\LoginController@unlock')->name('login.unlock');

Route::get('/',[
    'as' => 'index',
    'uses' => 'HomeController@index'
]);

Route::resource('employee','EmployeeController');

Route::get('settings',[
    'as' => 'settings',
    'uses' => 'SettingsController'
]);

Route::resource('user_role','UserRoleController');

Route::resource('module_permission','ModulePermissionController');

Route::resource('client','ClientController');

Route::resource('identity_card_type', 'IdentityCardTypeController');

Route::get('company',[
    'as' => 'company.show',
    'uses' => 'CompanyController@show'
]);

Route::resource('event', 'EventController', [
    'except' => [ 'show']
]);

Route::get('event/delete_event/{id}',[
    'as' => 'event.delete_event',
    'uses' => 'EventController@delete'
]);

Route::get('event/calander_view',[
    'as' => 'event.calander_view',
    'uses' => 'EventController@calander_view'
]);

Route::resource('product_unit', 'ProductUnitController');
Route::resource('product', 'ProductController');
Route::resource('supplier', 'SupplierController');
Route::resource('supply', 'SupplyController');
Route::resource('sell', 'SellController');

Route::resource('cashbook', 'CashBookController')->only([
    'index'
]);

Route::resource('stock', 'StockController')->only([
    'index'
]);

Route::get('stock/get_stock_by_product_id/{id}',[
    'as' => 'stock.get_stock_by_product_id',
    'uses' => 'StockController@getStockByProductId'
]);

Route::get('product/get_unit_by_id/{id}',[
    'as' => 'product.get_unit_by_id',
    'uses' => 'ProductController@getUnitById'
]);

Route::get('stock/stock_exists',[
    'as' => 'stock.stock_exists',
    'uses' => 'StockController@stockExists'
]);

Route::get('sell/{id}/print',[
    'as' => 'sell.print',
    'uses' => 'SellController@print'
]);

Route::get('stock/out_add_to_cart',[
    'as' => 'stock.out_add_to_cart',
    'uses' => 'StockController@outAddToCart'
]);

Route::get('stock/in_add_to_cart',[
    'as' => 'stock.in_add_to_cart',
    'uses' => 'StockController@inAddToCart'
]);

Route::get('stock/remove_from_cart/{id}',[
    'as' => 'stock.remove_from_cart',
    'uses' => 'StockController@removeFromCart'
]);

Route::get('stock/stock_check/{id}',[
    'as' => 'stock.stock_check',
    'uses' => 'StockController@getStockUnits'
]);

Route::get('stock/dashboard',[
    'as' => 'stock.dashboard',
    'uses' => 'StockController@dashboard'
]);

Route::get('stock/sell-graph-data',[
    'as' => 'stock.sell-graph-data',
    'uses' => 'StockController@sellGraphData'
]);


Route::resource('salary', 'SalaryController');
Route::resource('salary_period', 'SalaryPeriodController');

Route::get('salary/{id}/print',[
    'as' => 'salary.print',
    'uses' => 'SalaryController@print'
]);

Route::get('supply/{id}/print',[
    'as' => 'supply.print',
    'uses' => 'SupplyController@print'
]);

app/Http/Controllers/ProductUnitController.php
<?php

namespace App\Http\Controllers;

use App\Model\ProductUnit;
use App\Model\Settings;
use Illuminate\Http\Request;
use App\Util\CommonFunc;
use App\Type\StatusType;

class ProductUnitController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view', Settings::class);

        if($request['search-status'] == null){
            $request['search-status'] =StatusType::Active;
        }     
        
        $product_units = ProductUnit::select('mst_product_units.*')
                ->when(!empty($request->input('search-name')) , function ($query) use($request){
                    return $query->where('mst_product_units.name', 'like','%'. $request->input('search-name').'%' );
                })
                ->where('mst_product_units.status', '=',$request->input('search-status') )
                ->orderBy('insert_datetime', 'DESC')            
                ->paginate(CommonFunc::getPaginationSize());

        return view('product_unit.list')->with('product_units',$product_units)
                                     ->with('request',$request);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Settings::class);

        $product_unit = new ProductUnit();

        return view('product_unit.create')->with('product_unit',$product_unit);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Settings::class);

        $this->validate($request,[
            'name' => 'required|unique:mst_product_units',
            'display_name' => 'required|unique:mst_product_units',              
        ]);

        $product_unit= new ProductUnit;
        $product_unit->id=CommonFunc::getPrimaryKey();
        $product_unit->name=$request->input('name');
        $product_unit->display_name=$request->input('display_name');
        $product_unit->weight=$request->input('weight');
        $product_unit->status=StatusType::Active;
               
        $product_unit->save();

        return redirect()->route('product_unit.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ProductUnit  $productUnit
     * @return \Illuminate\Http\Response
     */
    public function show(ProductUnit $productUnit)
    {
        $this->authorize('view', Settings::class);

        return view('product_unit.view')->with('product_unit',$productUnit);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ProductUnit  $productUnit
     * @return \Illuminate\Http\Response
     */
    public function edit(ProductUnit $productUnit)
    {
        $this->authorize('view', Settings::class);

        return view('product_unit.create')->with('product_unit',$productUnit);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ProductUnit  $productUnit
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ProductUnit $product_unit)
    {
        $this->authorize('create', Settings::class);

        $this->validate($request,[
            'name' => 'required|unique:mst_product_units,name,'.$product_unit->id,
            'display_name' => 'required|unique:mst_product_units,display_name,'.$product_unit->id,              
        ]);

        $product_unit->name=$request->input('name');
        $product_unit->display_name=$request->input('display_name');
        $product_unit->weight=$request->input('weight');
        $product_unit->status=StatusType::Active;
        $product_unit->save();

        return redirect()->route('product_unit.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ProductUnit  $productUnit
     * @return \Illuminate\Http\Response
     */
    public function destroy(ProductUnit $productUnit)
    {
        //
    }
}

resources/views/product_unit/create.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <h1>
        Product Units
        <small>Handle all Product Units resources</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="{{ route('settings') }}"><i class="fa fa-cogs"></i> Settings</a></li>
        <li><a href="{{ route('product_unit.index') }}"><i class="fa fa-cogs"></i> Product Units</a></li>
        <li class="active">Product Unit Create</li>
    </ol>
</section>
<section class="content">
    <div class="container box">
        @if(!isset($product_unit->id))
        <div class="box-header">
            <h3 class="box-title">Product Unit Basic Information</h3>
        </div>
        <div class="box-body">
                {!! Form::open(['route' => ['product_unit.store'],'method' => 'POST','enctype' => 'multipart/form-data']) !!}
        @else
        <div class="box-header">
            <h3 class="box-title">Edit Product Unit Basic Information of :: <b>{{ $product_unit->display_name }} </b></h3>
        </div>
        <div class="box-body">
                {!! Form::open(['route' => ['product_unit.update',$product_unit->id],'method' => 'POST','enctype' => 'multipart/form-data']) !!}
                {!! Form::hidden('_method','PUT') !!}
        @endif
            <div class='form-group row'>
                {{Form::label('name','Name',['class' => 'col-sm-2 col-form-label text-md-right'])}}
                <div class="col-md-8">
                    {{Form::text('name', $product_unit->name ,['class' => 'form-control','placeholder'=>'Name','required'=> 'true'])}}
                    @if ($errors->has('name'))
                        <span class="invalid-feedback">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div> 
            </div>

            <div class='form-group row'>
                {{Form::label('display_name','Dispaly Name',['class' => 'col-sm-2 col-form-label text-md-right'])}}
                <div class="col-md-8">
                    {{Form::text('display_name', $product_unit->display_name ,['class' => 'form-control','placeholder'=>'Display Name','required'=> 'true'])}}
                    @if ($errors->has('display_name'))
                        <span class="invalid-feedback">
                            <strong>{{ $errors->first('display_name') }}</strong>
                        </span>
                    @endif
                </div> 
            </div>

            <div class='form-group row'>
                {{Form::label('weight','Weight(KG)',['class' => 'col-sm-2 col-form-label text-md-right'])}}
                <div class="col-md-8">
                    {{Form::number('weight', $product_unit->weight ,['class' => 'form-control','placeholder'=>'Weight(KG)','required'=> 'true'])}}
                    @if ($errors->has('weight'))
                        <span class="invalid-feedback">
                            <strong>{{ $errors->first('weight') }}</strong>
                        </span>
                    @endif
                </div> 
            </div>

        </div>               
    </div>            
</section>

<div class="row">
    <div class="form-group">
        <div class="col-sm-12 col-sm-offset-1">
            {{Form::reset('Reset',['class' => 'btn btn-default'])}}
            {{Form::submit('Submit',['class' => 'btn btn-primary'])}}
        </div>
    </div>    
</div>
<br>
<br>
{!! Form::close() !!}

<script type="text/javascript">
    $("#settings").addClass("active");
</script>

@endsection

resources/views/product_unit/list.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Product Units
            <small>Handle all Product Units resources</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{ route('settings') }}"><i class="fa fa-cogs"></i> Settings</a></li>
            <li class="active">Product Units</li>
        </ol>
    </section>
    <section class="content">
        <div class="container box">
            <div class="box-header">
                <h3 class="box-title">Product Unit List</h3> 
                <div class="semi pull-right">
                    <a href="{{ route('product_unit.create') }}" class="btn btn-success btn-xs" data-toggle="confirmation">
                        <i class="fa fa-pencil-square-o"></i> Add New
                    </a>
                </div>  
            </div>            
            <div class="box-body">
                {!! Form::open(['route' => 'product_unit.index','method' => 'GET','enctype' => 'multipart/form-data']) !!}
                    {{Form::label('search-name','Name',['class' => 'col-sm-1 control-label'])}}
                    
                    <div class="col-sm-3">
                        <div class="input-group">
                            {{Form::text('search-name', $request->input('search-name') ,['class' => 'form-control','placeholder'=>'Name'])}}
                            <span id="btnTextClear" class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                        </div>
                        <script>
                            $(".glyphicon-remove").click(function(){
                                $("#search-name").val('');
                            });
                        </script>
                    </div>

                    {{Form::label('search-status','Status',['class' => 'col-sm-1 control-label'])}}

                    <div class="col-sm-2">
                        {!!Form::select('search-status',App\Type\StatusType::getKeys(), $request->input('search-status'), ['class' => 'form-control'])!!}
                    </div>

                    <div class="col-sm-1">
                        {{Form::submit('Search',['class' => 'btn btn-info center-block'])}}
                    </div>
                {!! Form::close() !!}
                </div>
                @php ($i = 1)
                @if(count($product_units) > 0)
                <div class="table-responsive" style="overflow: auto">
                    <table id="dataTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Display Name</th>
                            <th>Weight(KG)</th>
                            <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($product_units as $product_unit)
                        <tr>
                            <td>{{ (($product_units->currentpage()-1) * $product_units->perpage()) + $i++  }}</td>
                            <td>{{$product_unit->name}}</td>
                            <td>{{$product_unit->display_name}}</td>
                            <td>{{$product_unit->weight}}</td>
                            <td title="{{ $product_unit->recordBy()}}">
                                <a href="{{ route('product_unit.show', ['id' => $product_unit->id]) }}" class="btn btn-info btn-xs">
                                    <i class="fa fa-info-circle"></i> View
                                </a>
                                <a href="{{ route('product_unit.edit', ['id' => $product_unit->id]) }}" class="btn btn-warning btn-xs" data-toggle="confirmation">
                                    <i class="fa fa-pencil-square-o"></i> Edit
                                </a>
                            </td>
                        </tr>
                        @endforeach    
                        </tbody>
                    </table>
                </div>
                {{ $product_units->appends(Request::except('page'))->links() }}
            @else
                <div class="alert alert-danger"> No Records Found ! </div>
            @endif
        </div>
    </section>

<script type="text/javascript">
    $("#settings").addClass("active");
</script>
@endsection

resources/views/product_unit/view.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Product Units
            <small>Handle all Product Units resources</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{ route('settings') }}"><i class="fa fa-cogs"></i> Settings</a></li>
            <li><a href="{{ route('product_unit.index') }}"><i class="fa fa-cogs"></i> Product Units</a></li>
            <li class="active">Product Unit View</li>
        </ol>
    </section>
    <section class="content">
        <div class="container box">
            <div class="box-header">
                <h3 class="box-title">Product Unit Deatails of :: <b>{{ $product_unit->name }} </b></h3>
                <div class="semi pull-right">
                    <a href="{{ route('product_unit.edit', ['id' => $product_unit->id]) }}" class="btn btn-warning btn-xs" data-toggle="confirmation">
                        <i class="fa fa-pencil-square-o"></i> Edit
                    </a>
                </div>    
            </div>
            <div class="box-body">
                <div class="col-md-6">
                    <div class="table-responsive">
                        <table class="table table-striped simple">
                            <tbody>                                            
                                <tr>
                                    <td>Name: </td>
                                    <td>{{ $product_unit->name }}</td>
                                </tr>
                                <tr>
                                    <td>Dispaly Name: </td>
                                    <td>{{ $product_unit->display_name }}</td>
                                </tr>
                                <tr>
                                    <td>Weight(KG): </td>
                                    <td>{{ $product_unit->weight }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="table-responsive">
                        <table class="table table-striped simple">
                            <tbody>                                             
                            </tbody>
                        </table>
                    </div>
                </div>
            </div> 
        </div>
    </section>   
    

<script type="text/javascript">
    $("#settings").addClass("active");
</script>
@endsection