routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('login/locked', 'Auth\LoginController@locked')->middleware('auth')->name('login.locked');
Route::post('login/locked', 'Auth\LoginController@unlock')->name('login.unlock');

Route::get('/',[
    'as' => 'index',
    'uses' => 'HomeController@index'
]);

Route::resource('employee','EmployeeController');

Route::get('settings',[
    'as' => 'settings',
    'uses' => 'SettingsController'
]);

Route::resource('user_role','UserRoleController');

Route::resource('module_permission','ModulePermissionController');

Route::resource('client','ClientController');

Route::resource('identity_card_type', 'IdentityCardTypeController');

Route::get('company',[
    'as' => 'company.show',
    'uses' => 'CompanyController@show'
]);

Route::resource('event', 'EventController', [
    'except' => [ 'show']
]);

Route::get('event/delete_event/{id}',[
    'as' => 'event.delete_event',
    'uses' => 'EventController@delete'
]);

Route::get('event/calander_view',[
    'as' => 'event.calander_view',
    'uses' => 'EventController@calander_view'
]);

Route::resource('product_unit', 'ProductUnitController');
Route::resource('product', 'ProductController');
Route::resource('supplier', 'SupplierController');
Route::resource('supply', 'SupplyController');
Route::resource('sell', 'SellController');

Route::resource('cashbook', 'CashBookController')->only([
    'index'
]);

Route::resource('stock', 'StockController')->only([
    'index'
]);

Route::get('stock/get_stock_by_product_id/{id}',[
    'as' => 'stock.get_stock_by_product_id',
    'uses' => 'StockController@getStockByProductId'
]);

Route::get('product/get_unit_by_id/{id}',[
    'as' => 'product.get_unit_by_id',
    'uses' => 'ProductController@getUnitById'
]);

Route::get('stock/stock_exists',[
    'as' => 'stock.stock_exists',
    'uses' => 'StockController@stockExists'
]);

Route::get('sell/{id}/print',[
    'as' => 'sell.print',
    'uses' => 'SellController@print'
]);

Route::get('stock/out_add_to_cart',[
    'as' => 'stock.out_add_to_cart',
    'uses' => 'StockController@outAddToCart'
]);

Route::get('stock/in_add_to_cart',[
    'as' => 'stock.in_add_to_cart',
    'uses' => 'StockController@inAddToCart'
]);

Route::get('stock/remove_from_cart/{id}',[
    'as' => 'stock.remove_from_cart',
    'uses' => 'StockController@removeFromCart'
]);

Route::get('stock/stock_check/{id}',[
    'as' => 'stock.stock_check',
    'uses' => 'StockController@getStockUnits'
]);

Route::get('stock/dashboard',[
    'as' => 'stock.dashboard',
    'uses' => 'StockController@dashboard'
]);

Route::get('stock/sell-graph-data',[
    'as' => 'stock.sell-graph-data',
    'uses' => 'StockController@sellGraphData'
]);


Route::resource('salary', 'SalaryController');
Route::resource('salary_period', 'SalaryPeriodController');

Route::get('salary/{id}/print',[
    'as' => 'salary.print',
    'uses' => 'SalaryController@print'
]);

Route::get('supply/{id}/print',[
    'as' => 'supply.print',
    'uses' => 'SupplyController@print'
]);

app/Http/Controllers/SettingsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\Settings;

class SettingsController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $this->authorize('view', Settings::class);

        return view('settings.dashboard');
    }
}

resources/views/settings/dashboard.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Settings
            <small>Handle all Settings</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Settings</li>
        </ol>
    </section>
    <section class="content">
        <div class="container box"> 
            <div class="col-md-4" style="padding: 10px;"> 
                <a href="{{ route('user_role.index') }}" class="material-main-select-blue">
                    <ol>
                        <li>User Role</li>
                    </ol>
                </a>
            </div>
            <div class="col-md-4" style="padding: 10px;"> 
                <a href="{{ route('module_permission.index') }}" class="material-main-select-green">
                    <ol>
                        <li>Module Permission</li>
                    </ol>
                </a>
            </div>
            <div class="col-md-4" style="padding: 10px;"> 
                <a href="{{ route('identity_card_type.index') }}" class="material-main-select-orange">
                    <ol>
                        <li>Identity Card Type</li>
                    </ol>
                </a>
            </div>
            <div class="col-md-4" style="padding: 10px;"> 
                <a href="{{ route('product_unit.index') }}" class="material-main-select-red">
                    <ol>
                        <li>Product Unit</li>
                    </ol>
                </a>
            </div>
            
            <div class="col-md-4" style="padding: 10px;"> 
                <a href="{{ route('salary_period.index') }}" class="material-main-select-yellow">
                    <ol>
                        <li>Salary Period</li>
                    </ol>
                </a>
            </div>
           
        </div>
    </section>   
    

<script type="text/javascript">
    $("#settings").addClass("active");
</script>
@endsection